# Generated by Django 3.2.7 on 2021-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210927_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw6',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='calculatedstudent',
            name='aw7',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sylb',
            field=models.CharField(default='N/N', max_length=3, null=True),
        ),
    ]
