# Generated by Django 3.2.7 on 2021-10-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_student_raw_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatedstudent',
            name='aggr',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='comp_ind1',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='comp_ind2',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='division',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='grade2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='grade3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='grade4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='grade5',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='marksheet_no',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='overall_grade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='total2',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='total3',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='total4',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='calculatedstudent',
            name='total5',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
