# Generated by Django 3.2.7 on 2021-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211004_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pr_ab',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='th_ab',
            field=models.BooleanField(default=False),
        ),
    ]
