from django.db import models

class Student(models.Model):
	school = models.CharField(max_length=5)
	enr_no = models.CharField(max_length=10)
	enr_yr = models.CharField(max_length=4)
	roll_no = models.CharField(max_length=12)
	stream = models.CharField(max_length=1)
	name = models.CharField(max_length=35)
	sub1 = models.CharField(max_length=2, null=True)
	th1 = models.CharField(max_length=3, null=True)
	pr1 = models.CharField(max_length=2, null=True)
	sub2 = models.CharField(max_length=2)
	th2 = models.CharField(max_length=3, null=True)
	pr2 = models.CharField(max_length=2)
	sub3 = models.CharField(max_length=2)
	th3 = models.CharField(max_length=3, null=True)
	pr3 = models.CharField(max_length=2)
	sub4 = models.CharField(max_length=2)
	th4 = models.CharField(max_length=3, null=True)
	pr4 = models.CharField(max_length=2)
	sub5 = models.CharField(max_length=2)
	th5 = models.CharField(max_length=3, null=True)
	pr5 = models.CharField(max_length=2)
	sub6 = models.CharField(max_length=2, null=True)
	th6 = models.CharField(max_length=3, null=True)
	pr6 = models.CharField(max_length=2, null=True)
	sub7 = models.CharField(max_length=2, null=True)
	th7 = models.CharField(max_length=3, null=True)
	pr7 = models.CharField(max_length=2, null=True)
	exception_code = models.CharField(max_length=1, null=True)
	absent_code = models.CharField(max_length=1, null=True)
	incomplete_code = models.CharField(max_length=1, null=True)

	def __str__(self):
		return self.enr_no

class CalculatedStudent(models.Model):
	student = models.OneToOneField(Student, on_delete=models.CASCADE)
	total1 = models.CharField(max_length=3, null=True)
	grade1 = models.CharField(max_length=2, null=True)
	total2 = models.CharField(max_length=3)
	grade2 = models.CharField(max_length=2)
	total3 = models.CharField(max_length=3)
	grade3 = models.CharField(max_length=2)
	total4 = models.CharField(max_length=3)
	grade4 = models.CharField(max_length=2)
	total5 = models.CharField(max_length=3)
	grade5 = models.CharField(max_length=2)
	total6 = models.CharField(max_length=3, null=True)
	grade6 = models.CharField(max_length=2, null=True)
	total7 = models.CharField(max_length=3, null=True)
	grade7 = models.CharField(max_length=2, null=True)
	aggr = models.CharField(max_length=3)
	overall_grade = models.CharField(max_length=2)
	division = models.CharField(max_length=1)
	comp_ind1 = models.CharField(max_length=1)
	comp_ind2 = models.CharField(max_length=1)
	marksheet_no = models.CharField(max_length=6)
	cert_no = models.CharField(max_length=6, null=True)

	def __str__(self):
		return self.student.enr_no